kind: pipeline
name: default

steps:
- name: deno_land
  image: ubuntu:18.04
  commands:
  - apt-get update && apt-get install curl unzip -y
  - curl -fsSL https://deno.land/x/install/install.sh | sh
  - /root/.deno/bin/deno --version
